#!/bin/sh

# ssh-add -K ~/.ssh/id_rsa

export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Paths
PATH=$PATH:/usr/local/bin
PATH=$PATH:$HOME/go/bin
PATH=$PATH:/usr/local/opt/go/libexec/bin
PATH=$PATH:$HOME/dotfiles/bin
PATH=$PATH:$HOME/dotfiles/apps/bin

# shellcheck source=$HOME/.zim/init.zsh
[ -f ${ZIM_HOME}/init.zsh ] && . ${ZIM_HOME}/init.zsh

zstyle ':vcs_info:git:*:-all-' command =git

# Set PROJECT_DIR to the path where your projects exist.
[ -z "$PROJECT_DIR" ] && export PROJECT_DIR=~/Sites

# Set Atom as default editor
export EDITOR="atom-beta"
export ATOM_PATH="/Applications"

# Set homebew cask options
export HOMEBREW_CASK_OPTS="--appdir=/Applications --fontdir=/Library/Fonts"

# Use PHP71
export PATH
PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"

# Go path
export GOPATH=$HOME/go

# Bash completion
autoload bashcompinit
bashcompinit
. /usr/local/etc/bash_completion.d/wp-completion.bash
# . /usr/local/etc/bash_completion.d/youtube-dl.bash-completion
# fpath=(/usr/local/share/zsh-completions $fpath)

# Node
export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export NODE_ENV="development"

# shellcheck source=/usr/local/opt/nvm/nvm.sh
. "$(brew --prefix nvm)/nvm.sh"

# shellcheck source=$HOME/dotfiles/zsh/aliases
[ -f $HOME/dotfiles/zsh/aliases ] && . $HOME/dotfiles/zsh/aliases

# shellcheck source=$HOME/dotfiles/zsh/functions
[ -f $HOME/dotfiles/zsh/functions ] && . $HOME/dotfiles/zsh/functions
